language: python

python: "2.7"

env:
  - DJANGO=https://github.com/django/django/zipball/master
  - DJANGO=django==1.5.5 --use-mirrors
  - DJANGO=django==1.4.3 --use-mirrors
  - DJANGO=django==1.3.5 --use-mirrors

install:
  - pip install $DJANGO
  - pip install redis
  - export PYTHONPATH=.

script:
  - python manage.py test user_streams
